name: release

on:
  workflow_dispatch:

env:
  CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
    auditwheel repair -w {dest_dir} {wheel} &&
    pipx run abi3audit --strict --report {wheel}
  CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
    delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel} &&
    pipx run abi3audit --strict --report {wheel}
  CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
    pipx run abi3audit --strict --report {wheel}

jobs:

  sdist:
    name: Package source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: sdist
        run: python setup.py sdist -d package

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.tar.gz

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64

      - name: deps
        run: python -m pip install cibuildwheel==2.16.2

      - name: wheels
        run: python -m cibuildwheel --output-dir package

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.whl
